name: ollama

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - open-webui_ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - open-webui_default

volumes:
  open-webui_ollama:
    external: true # Criar volume antes: docker volume create open-webui_ollama

networks:
  open-webui_default:
    external: true